# Generated by Django 4.2 on 2023-05-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_devicedata_battery_level_devicedata_battery_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedata',
            old_name='battery_level',
            new_name='batteryLevel',
        ),
        migrations.RenameField(
            model_name='devicedata',
            old_name='battery_status',
            new_name='batteryStatus',
        ),
        migrations.RenameField(
            model_name='devicedata',
            old_name='location_horizontal_accuracy',
            new_name='location_horizontalAccuracy',
        ),
        migrations.RenameField(
            model_name='devicedata',
            old_name='location_is_inaccurate',
            new_name='location_isInaccurate',
        ),
        migrations.RenameField(
            model_name='devicedata',
            old_name='location_is_old',
            new_name='location_isOld',
        ),
        migrations.RenameField(
            model_name='devicedata',
            old_name='location_finished',
            new_name='location_locationFinished',
        ),
        migrations.RenameField(
            model_name='devicedata',
            old_name='location_position_type',
            new_name='location_positionType',
        ),
        migrations.RenameField(
            model_name='devicedata',
            old_name='location_timestamp',
            new_name='location_timeStamp',
        ),
        migrations.RenameField(
            model_name='devicedata',
            old_name='location_vertical_accuracy',
            new_name='location_verticalAccuracy',
        ),
    ]
